name: Send API Response to Repo

on:
  push:

jobs:
  send-response:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code using PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Call API and save to file
        run: |
          curl -X POST https://shams.sython.ir/test.php \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "name=Aliresa mazrae - Amirhossein Rajabi" \
            -d "student_code=03121033705044 - 03121033705035" \
            -o response.txt

      - name: Setup Git and Push response.txt
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Change the origin URL to use PAT for auth
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}

          git add response.txt
          git commit -m "Save API response" || echo "Nothing to commit"
          git push origin HEAD:${{ github.ref }}
