name: Send Data to API and Save Response

on:
  push:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Call API and save response to file
        run: |
          curl -X POST https://shams.sython.ir/test.php \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "name=Aliresa mazrae - Amirhossein Rajabi" \
            -d "student_code=03121033705044 - 03121033705035" \
            -o response.txt

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit and push response.txt using PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add response.txt
          git commit -m "Save API response"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
