name: Send Data to API on Commit with token getting

on:
  push:  # Trigger on every push

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call your API with name and student_code
        run: |
          curl -X POST https://shams.sython.ir/test.php \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "name=Aliresa mazrae - Amirhossein Rajabi" \
            -d "student_code=03121033705044 - 03121033705035"
